import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AppShell, AppShellMain, MantineProvider, Title } from '@mantine/core'
import { theme } from './theme'
import '@mantine/core/styles.css'
import Header from './components/Header'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Domanu',
  description: 'Generated by create next app',
}

async function getSession() {
  try {
    const response = await fetch('http://localhost:8000/auth/session', {
      credentials: 'include',
    });
    
    if (!response.ok) {
      throw new Error('Failed to fetch session');
    }
    
    const data = await response.json();
    return data.message;
    
  } catch (error) {
    console.error('Error fetching session:', error);
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider defaultColorScheme="light" theme={theme}>
          <main className="min-h-full">
            <AppShell header={{ height: 120 }} padding="md">
              <Header session={session.user} />
              <AppShellMain>
                {children}
              </AppShellMain>
            </AppShell>
          </main>
        </MantineProvider>
      </body>
    </html>
  )
}
